---
url: https://frontwebconf.prismic.io/api
# If specified this token is used for all "guest" requests
# token: ""
# OAuth2 configuration
client_id: "Ury0FQEAAPn4pbYT"
client_secret: "dc50f199cc05ef9d786dd74fa5c4ef44"
